data_root: data/rgbd_dataset_freiburg1_teddy/ # the following args are relative to data_root(if not absolute path)
data_type: fr1  # determind the data format
tum:
    rgb_data: rgb/  # rgb data root
    depth_data: depth/  # depth data root

    rgb_file: rgb.txt # rgb index file
    depth_file: depth.txt # depth index file
    gt_file: groundtruth.txt # groundtruth file

    associate_file: associate.txt # associate output file
    match_tolerance: 0.02 # match tolerance for associate
    match_offset: 0.0 # time offset added to the timestamps of the second file when associating

    camera_factor: 5000.0 # depth image scale
bilateral_filter:
    diameter: 5
    sigma_color: 50
    sigma_space: 50